### ISSUE TITLE
Regular LUA errors on load and mouseover

### ISSUE THREAD

**Issue by jtkimbell** [McPewPew/Bagnon#1]
My apologies if you'd prefer I don't file an issue. I was unsure how to get in touch. While playing Turtle WoW I installed the latest version of Bagnon (had used a differently version prior) from here. It functions the same, but I get LUA errors in 3 situations:

**1) On first load of my bags:**
![image](https://user-images.githubusercontent.com/44843397/236123915-c5659a8b-d863-4952-809f-d9c888bcda4a.png)

The second attempt to open my bags will succeed with no error.

**2) When hovering over where the title should be**
![image](https://user-images.githubusercontent.com/44843397/236124017-36d72264-b1e4-4d79-82c4-d23619599b5c.png)
![image](https://user-images.githubusercontent.com/44843397/236124045-59f50abd-6bbf-4bf6-a2df-35575fe88b8c.png)

This happens every time my mouse goes over the area above the bag slots.

**3) When attempting to open my bank**
![image](https://user-images.githubusercontent.com/44843397/236124176-cad57ac9-105b-44e3-8c6b-d76105d15ff7.png)

After this error, my backpack opens, but not my bank. I have to close my backpack and then the bank will open. This error appears every time I try to open my bank:
![image](https://user-images.githubusercontent.com/44843397/236124324-0b07ecb4-e8e0-4799-9862-107d67758aaa.png)

**Comment by bushtail** [comment]
Issue seems to be localized to Bagnon Forever. Unload it, and things work.

**Comment by jtkimbell** [comment]
> Issue seems to be localized to Bagnon Forever. Unload it, and things work.

Yes, that seemed to fix it, thanks!
